Repository googleapis/nodejs-billing, pull requests merged in 2020-06, with the labels that each got.

#56 fix: update common protos and fix synth
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
  synth.py
Labels: cla: yes

#59 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/cloud_billing_client.ts
  src/v1/cloud_catalog_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#62 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#63 fix: proper fallback option handling
  src/v1/cloud_billing_client.ts
  src/v1/cloud_catalog_client.ts
  synth.metadata
Labels: cla: yes, context: none

#64 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#66 build: add config .gitattributes
  .gitattributes
  .kokoro/.gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
