Repository googleapis/nodejs-billing, pull requests merged in 2020-11, with the labels that each got.

#110 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#111 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/cloud_billing_client.ts
  src/v1/cloud_catalog_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudbilling, automerge, cla: yes

#113 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/cloud_billing_client.ts
  src/v1/cloud_catalog_client.ts
  synth.metadata
Labels: api: cloudbilling, cla: yes, context: none
